import type { Metadata } from 'next'
import { Geist, Spectral } from 'next/font/google'
import './globals.css'

const serifFont = Spectral({
  variable: '--font-spectral',
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
})

const sansFont = Geist({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${sansFont.className} ${serifFont.variable} antialiased bg-[#e0d3bf]`}>{children}</body>
    </html>
  )
}
